### ISSUE TITLE
Error updating config: failed to unmarshal config: yaml: line 91: did not find expected key

### ISSUE THREAD

**Issue by Happyfeet01** [YunoHost-Apps/mautrix_whatsapp_ynh#111]
### Describe the bug

Yunohost is trying to update Whatsapp Bridge. This results in the error as shown in the error log below. A restore of the backup is successfully restored

### Context

- Hardware: *Dedicated Server,  Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz, 64 GB RAM, 4 TB Storage*
- YunoHost version: 11.2.3
- I have access to my server: *SSH, Yunohost Panel, Webmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
- If upgrading, current package version: 
- 
    description: Matrix / Synapse puppeting bridge for WhatsApp
    id: mautrix_whatsapp
    name: Matrix-WhatsApp bridge
    version: 0.8.6~ynh1

### Steps to reproduce

   1. *Go to 'Update System'*
   2. *when an Whatsapp Bridge update is available, click on update*
   3. *Wait for finishing the update*
   4. *See the error*

### Expected behavior

*I expect the Whatsapp bot to work again and the update to work without error message.*

### Logs
 https://paste.yunohost.org/raw/qarofenivu

**Comment by thardev** [comment]
Hi @Happyfeet01 

I checked the logs and this kind of error usually happens when the `config.yaml` file is not valid after the values from your `settings.yml` are applied. I'll try to reproduce it but in my instance the upgrade worked fine, I'll try on my dev box as well.

Could you paste a copy of your current `config.yaml`? **Please remove before any sensitive info from it**

**Comment by Happyfeet01** [comment]
Here is my config.yaml

https://paste.yunohost.org/cubenavoxu.coffeescript

**Comment by Happyfeet01** [comment]
Any Update?

**Comment by thardev** [comment]
Hi @Happyfeet01 

Sorry for the delay, I've checked your config file but everything seems ok...
Could you maybe post the contents of your `/etc/yunohost/apps/mautrix_whatsapp/settings.yml` ?

⚠️ **Carefully remove any password you see inside that file before posting it** ⚠️

**Comment by Happyfeet01** [comment]
@thardev Here is the content https://paste.yunohost.org/jagutapufe.go

**Comment by thardev** [comment]
Ok, could you try the following:

`yunohost app setting mautrix_whatsapp db_pwd -v {VALUE_OF_YOUR_PSQLPWD_KEY}`
You have the value inside your `settings.yml` file.

Also:
`yunohost app setting mautrix_whatsapp db_user -v mautrix_whatsapp`

Then try to upgrade again 🙂

**Comment by thardev** [comment]
I will close this for now, feel free to reopen it if the error persists or you need more help 🙂
