### ISSUE TITLE
[support] Syntax for permission

### ISSUE THREAD

**Issue by ghost** [YunoHost-Apps/mautrix_whatsapp_ynh#12]
Hi all,

I would like to ask for help with the config syntax.
In the install gui I setup user xyz:mydomain.tld as admin and set the permission to use this bridge to local by entering local.

No if I try to setup a Bridge by inviting the bot to a room I get back, that I don't have the permission and the wabot leaves the room.

When I no try to change the config.yaml file I do get an error for wrong syntax.

Help is appreciated

(By the way I once uninstalled the app and installed it again because of this problem with the syntax)

**Comment by Gredin67** [comment]
Hi,
Indeed there was a typo in the install script. I modified it in the testing branch, so could you remove the app and then reinstall it using: 
``sudo yunohost app install https://github.com/YunoHost-Apps/mautrix_whatsapp_ynh/tree/testing``

If you use ``local``, all users with your synapse server name``synapse_server_name.tld`` should have access. 
The syntax in ``config.yaml`` is following:
```
  permissions:
    '*': 5
    '@adminuser:anydomain.tl': 100
    '@adminuser:synapse_server_name.tld': 100
    authorizeduser.domain: 10
```
Then you probably have to restart the bot:
``sudo service mautrix_whatsapp restart``

**Comment by ghost** [comment]
Hey thanks for the quick response!

I tried the testing branch and the permissions are now set as expected.
