### ISSUE TITLE
Upgrading failed as matrix-synapse user doesn't exist anymore

### ISSUE THREAD

**Issue by Thatoo** [YunoHost-Apps/mautrix_whatsapp_ynh#142]
### Describe the bug

Trying to update from v 0.10.5~ynh1 to 0.10.6~ynh1  after upgrading to the latest version of synapse fails.

### Context

- Hardware:  Old laptop or computer
- YunoHost version: 11.2.11.2
- I have access to my server: Through SSH | through the webadmin | direct access via keyboard / screen 
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no 
- Using, or trying to install package version/branch: 0.10.6~ynh1 
- If upgrading, current package version:  0.10.5~ynh1

### Steps to reproduce

- upgrade synapse to v 1.104.0~ynh1
- `matrix-synapse` user is replaced by `synapse` user
- trying to upgrade mautrix_telegram
- upgrade fails because : `2024-04-20 09:13:33,283: WARNING - chown: utilisateur incorrect: « matrix-synapse »
`

### Expected behavior

upgrade succes

**Comment by thardev** [comment]
Hi @Thatoo 

Could you try again the upgrade process? I think there were some changes in the Synapse package and it broke the upgrade for a while. I tested it on my local dev machine and it the pipeline and it seems to be working now.
See: #140 (Ignore the latest pipeline, the green one should be the relevant one)

**Comment by Thatoo** [comment]
Well, update is not offered anymore as mautrix_whatsapp_ynh package status is Broken..

**Comment by thardev** [comment]
I'm checking it again, it seems that for Bullseye the pipeline worked but not for Bookworm 🤔 I need to check what's going on, it seems something about the manifest but it shouldn't be related to this issue.

**Comment by Dazeilad** [comment]
Hi, is it possible to make it available for Bullseye at least ?

**Comment by thardev** [comment]
Hi @Dazeilad @Thatoo 

It should be already available for Bullseye, please test and let me know if it works so I can close this 🙂

**Comment by Thatoo** [comment]
I just did the update and it seems to be working.

**Comment by thardev** [comment]
I'll close it then, feel free to reopen it if the error persist or appears again 🙂
