### ISSUE TITLE
conduit

### ISSUE THREAD

**Issue by chri2** [YunoHost-Apps/mautrix_whatsapp_ynh#154]
conduit is not mentioned. I'm running conduit and I'm really happy with the low ressource profile it has and the way it works.

Would the package support conduit as well?

**Comment by Gredin67** [comment]
see https://github.com/YunoHost-Apps/conduit_ynh

**Comment by chri2** [comment]
Yes, I'm running already conduit_ynh. But does this package for the mautrix whatsapp bridge support conduit as a replacement of synapse?

**Comment by Gredin67** [comment]
I'm not sure conduit is supporting app_service properly. I once did some preliminary work to support dendrite :
https://github.com/YunoHost-Apps/mautrix_signal_ynh/pull/85

For sure you can already try to install an instance of mautrix_whatsapp and tweak the homeserver config in the bridge config.yaml file.

Le 26 août 2024 09:12:23 GMT+02:00, Chris Vogel ***@***.***> a écrit :

**Comment by chri2** [comment]
Thanks, that is really interesting. I'm already running the bridge as a docker container using the conduit_ynh.

I'd like to migrate the bridge sometimes to a native yunohost app - that's why I asked.

I would prefer if we'd extend this package to support conduit as well - if there is any change needed at all. I'll look into it when I find time.
