### ISSUE TITLE
How to update?

### ISSUE THREAD

**Issue by bjesus** [YunoHost-Apps/mautrix_whatsapp_ynh#16]
Hi! thanks for the great package. while maybe not being 100% production ready, it still makes the process of setting up mautrix-whatsapp much easier.

A new version of mautrix-whatsapp came out recently. I'm wondering - how should one update? `/opt/yunohost/mautrix_whatsapp` seem to hold all files but it's not a git repo, so I'm not sure how to pull and recompile. Any pointers?

**Comment by Gredin67** [comment]
indeed I mainly focused on the install (and a bit deinstall) script up to now, which still requires some adjustment in coordination with the Yunohost synapse maintainer @Josue-T . Apps packaged for YunoHost require to download a zip from a release version of the upstream app. I think pulling with git is bad practice.
To update, the new release should be downloaded and then ``git build`` (master branch) ``./build.sh`` (buster branch). Then restart mautrix-whatsapp service. Feel free to write the upgrade script in this repo.

**Comment by Gredin67** [comment]
upgrade script was tested successfully
