### ISSUE TITLE
New version

### ISSUE THREAD

**Issue by L-S-2020** [YunoHost-Apps/mautrix_whatsapp_ynh#24]
Hello,
thanks for this nice Yunohost APP,
but since yesterday it don't work, I only get this error: 
Unknown error while logging in: error decoding login resp: json: cannot unmarshal array into Go value of type map[string]interface {}
In the upstream reponsitory there's an update to fix this. Can you please update it?
Thanks for your help

**Comment by Gredin67** [comment]
fingers crossed #25

**Comment by L-S-2020** [comment]
I've installed the bridge over the testing tree and it works!
Thank you

**Comment by Gredin67** [comment]
yep, finally! But the upgrade is not working yet, so I will wait before merging in master.

**Comment by L-S-2020** [comment]
I think it's not only the upgrade, my bridge is running but it don't works and there isn't any error in the logs. When I write a message in a room or to the whatsappbridgebot I don't get any answer.

**Comment by Gredin67** [comment]
What did you do/try exactly?

did you check your config file ?
``sudo nano /opt/yunohost/mautrix_whatsapp/config.yaml``?
Can you send the ``/var/log/mautrix_whatsapp/log.log``?

**Comment by L-S-2020** [comment]
Maybe I was it self, because I've edit the permisions in the config file, but in the logs weren't an error. The problem that I've uninstalled the Bridge so I haven't got any logs. Sorry, but I will give it a second trial.
