### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by meowIAmAUser** [YunoHost-Apps/mautrix_whatsapp_ynh#30]
### Describe the bug

If i try to install the Bridge, it doesn't work and say's "Corrupt Source

### Context

- Hardware: Regular Computer x64
- YunoHost version: 4.2.6.1
- I have access to my server: Through SSH | through the webadmin | direct access via keyboard / screen
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
- Using, or trying to install package version/branch: 0.1.7~ynh3

### Steps to reproduce

Install the App through the Webadmin in the normal App Catalog

### Expected behavior

It should install

### Logs
https://paste.yunohost.org/raw/isifitiweb

**Comment by lucyferu** [comment]
Sadly, I'm having the same issue.
Log can be found **[here](https://paste.yunohost.org/raw/lotiyazuta)**.

**Comment by Gredin67** [comment]
please try out the testing branch
``sudo yunohost install https://github.com/YunoHost-Apps/mautrix_whatsapp_ynh/tree/testing``

**Comment by meowIAmAUser** [comment]
I was able to install it.
However, I named by Bot “WhatsApp”, but Element say's, that this user does not exist.

**Comment by meowIAmAUser** [comment]
### Element notice (German)
![Bildschirmfoto von 2021-08-14 11-56-20](https://user-images.githubusercontent.com/85834680/129442331-341d45df-22aa-47f7-81cf-069a9d45259a.png)
### My Config.yaml
![Bildschirmfoto von 2021-08-14 11-56-47](https://user-images.githubusercontent.com/85834680/129442333-da81ffe5-f5c3-42fd-a494-c11e54893dcd.png)

**Comment by meowIAmAUser** [comment]
Here are my Logs: [bin.snopyta.org](https://bin.snopyta.org/?5451d5dd1b6fba85#8JcrDgYAoA4gLTbA9itMs2tAKScyfCQvYy1JxKKFe8rw)

Also, my Ports 5349 and 8448 aren't open. Could that be the Problem?

**Comment by Gredin67** [comment]
ports do not need to be open as synapse and the bridge communicate locally. 
Did you restart synapse and mautrix?
Which token do you have in ``/etc/matrix-synapse/app-service/mautrix_whatsapp.yaml`` ?

**Comment by Gredin67** [comment]
I would suggest you retry to install with the standard parameters ``whatsappbot``, etc. Make sure that all mautrix_whatsapp instances have been removed.
