### ISSUE TITLE
Public key is not available

### ISSUE THREAD

**Issue by SpiderOnTheNet** [YunoHost-Apps/mautrix_whatsapp_ynh#32]
Hi, I got trouble to install this package.

I got a RPI on with YunoHost, when I try to install the bridge with YunoHost api it give me this error :

```
Info: DEBUG - + apt-get --assume-yes --quiet -o=Acquire::Retries=3 -o=Dpkg::Use-Pty=0 update
Info: DEBUG - Hit:1 http://127.0.0.1:9977/raspbian.raspberrypi.org/raspbian buster InRelease
Info: DEBUG - Hit:2 http://127.0.0.1:9977/archive.raspberrypi.org/debian buster InRelease
Info: DEBUG - Hit:3 http://127.0.0.1:9977/forge.yunohost.org/debian buster InRelease
Info: DEBUG - Get:4 http://cdn-fastly.deb.debian.org/debian buster-backports InRelease [46.7 kB]
Info: DEBUG - Err:4 http://cdn-fastly.deb.debian.org/debian buster-backports InRelease
Info: DEBUG -   The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 648ACFD622F3D138 NO_PUBKEY 0E98404D386FA1D9
Info: DEBUG - Reading package lists...
Info: WARNING - W: GPG error: http://cdn-fastly.deb.debian.org/debian buster-backports InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 648ACFD622F3D138 NO_PUBKEY 0E98404D386FA1D9
Info: WARNING - E: The repository 'http://http.debian.net/debian buster-backports InRelease' is not signed.
Info: DEBUG - + ynh_exit_properly
```
When I force to update "http://cdn-fastly.deb.debian.org/debian buster-backports InRelease" without the rpg key, it make YunoHost wrong (can't install new app...). So I reinstall a new YnoHost image on my RPI :/

So this time I tried to download the testing branch :
`git clone --single-branch -b testing https://github.com/YunoHost-Apps/mautrix_whatsapp_ynh.git`

And install it in ssh with "yunohost" command :
`sudo yunohost app install mautrix_whatsapp`

But I got the same error :
```
Info: WARNING - W: GPG error: http://cdn-fastly.deb.debian.org/debian buster-backports InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 648ACFD622F3D138 NO_PUBKEY 0E98404D386FA1D9
Info: WARNING - E: The repository 'http://http.debian.net/debian buster-backports InRelease' is not signed.
```

I did something wrong ? :/

**Comment by alexAubin** [comment]
Same issue reported on https://forum.yunohost.org/t/unable-to-install-mautrix-whatsapp-and-discord-bridge

**Comment by Gredin67** [comment]
Is there a cleaner solution for RPi than manually running `sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 0E98404D386FA1D9` ?

**Comment by alexAubin** [comment]
There's a `--key` arg to ynh_install_extra_deps (i dont remember the exact helper name) where you could feed an https url for the corresponding key

**Comment by Gredin67** [comment]
@alexAubin Should this work #36 ? Or do I have to give https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x1f89983e0081fde018f3cc9673a4f27b8dd47936

**Comment by alexAubin** [comment]
@Gredin67 : you have to provide the full url containing the gpg key, yes, not just ` --key="https://keyserver.ubuntu.com"`

**Comment by Gredin67** [comment]
@SpiderOnTheNet can you try 
`sudo yunohost app install -u https://github.com/YunoHost-Apps/mautrix_whatsapp_ynh/tree/testing --debug`
