### ISSUE TITLE
Expose config.yaml parameters in new config panel

### ISSUE THREAD

**Issue by Gredin67** [YunoHost-Apps/mautrix_whatsapp_ynh#33]
YunoHost-Apps/mautrix_signal_ynh/issues/24

**Comment by thardev** [comment]
I'm on it 🙂 but user management part takes long to implement...

**Comment by Gredin67** [comment]
That would be awesome! Don't hesitate to ask for help on the yunohost apps chat, particularly ljf.
We could even organize a small call to have a look at the difficulties together! I'm pretty sure @Josue-T would be interested in getting a config panel for [synapse](https://github.com/YunoHost-Apps/synapse_ynh/issues/284)
