### ISSUE TITLE
Unknown error while logging in: error decoding login resp ["Cmd",{"type":"update"}]

### ISSUE THREAD

**Issue by svenbrier** [YunoHost-Apps/mautrix_whatsapp_ynh#34]
Hello, the bot suddenly stopped working and gave the following error message:

Unknown error while logging in: error decoding login resp ["Cmd",{"type":"update"}]: json: cannot unmarshal array into Go value of type map[string]interface {}
Your WhatsApp connection was closed with websocket status code 1000. Use the reconnect command to reconnect.

The raw data is:
<pre>{
  "type": "m.room.message",
  "room_id": "!abcdefg1234567:foo.com",
  "sender": "@whatsappbot:foo.com",
  "content": {
    "msgtype": "m.text",
    "body": "Your WhatsApp connection was closed with websocket status code 1000. Use the `reconnect` command to reconnect.",
    "format": "org.matrix.custom.html",
    "formatted_body": "Your WhatsApp connection was closed with websocket status code 1000. Use the <code>reconnect</code> command to reconnect."
  },
  "origin_server_ts": 123456789,
  "unsigned": {
    "age": 182
  },
  "event_id": "$abc-a0_AbCK-abc123",
  "user_id": "@whatsappbot:foo.com",
  "age": 182
}</pre>

Have you any Idea, what could cause the problem?

**Comment by L-S-2020** [comment]
I have the same problem

**Comment by h3ndrik** [comment]
same problem here. seems to be the bridge that has to be updated. i've just now downloaded v0.1.9 manually and that version works.

for reference, what i did to replace the binary to do a quick and dirty fix:
```
wget https://github.com/mautrix/whatsapp/releases/download/v0.1.9/mautrix-whatsapp-amd64
service mautrix_whatsapp stop
mv /opt/yunohost/mautrix_whatsapp/mautrix-whatsapp /opt/yunohost/mautrix_whatsapp/mautrix-whatsapp.old
mv mautrix-whatsapp-amd64 /opt/yunohost/mautrix_whatsapp/mautrix-whatsapp
chown mautrix_whatsapp.root /opt/yunohost/mautrix_whatsapp/mautrix-whatsapp
chmod 755 /opt/yunohost/mautrix_whatsapp/mautrix-whatsapp
service mautrix_whatsapp start
```

**Comment by svenbrier** [comment]
Thank you h3ndrik! This fixes the problem for me :D Even if it's quick and dirty. ;)

**Comment by Gredin67** [comment]
@h3ndrik next time feel free to upgrade the Yunohost package rather than hacking on your own... See #35, it is probably even faster than finding/applying you hack!

If you use Yunohost you could try to contribute a bit...

**Comment by h3ndrik** [comment]
> @h3ndrik next time feel free to upgrade the Yunohost package rather than hacking [...}

thank you. will do that.
