### ISSUE TITLE
Looking for a maintainer

### ISSUE THREAD

**Issue by Gredin67** [YunoHost-Apps/mautrix_whatsapp_ynh#43]
Upgrading to 0.2.1 will be my last contribution as a maintainer. Any volunteer to take over maintenance of the package? I feel like it is going to be much easier now that the upstream app is much more stable, so should not be a big deal.

**Comment by thardev** [comment]
Hi @Gredin67

I'll be up for mantaining it.
I'm familiar with the packaging architecture and also I think I have the necessary skills.
In the past I started packaging some apps but never actually published them, but I'll be happy to contribute to this one :)

**Comment by Gredin67** [comment]
@thardev can you please upgrade to 0.3.0 ? If you need some help let me know
Don't forget to upgrade the config.yaml file https://github.com/mautrix/whatsapp/compare/v0.2.4...v0.3.0

**Comment by Gredin67** [comment]
as a maintainer it would be nice if you could solve #33 you can ping @zamentur for help

**Comment by thardev** [comment]
Ok! 😄 Will work on it soon! :)
