### ISSUE TITLE
ERROR : Failed to log in: unexpected connection event from server

### ISSUE THREAD

**Issue by rosbeef** [YunoHost-Apps/mautrix_whatsapp_ynh#47]
### Describe the bug

*Failed to log in: unexpected connection event from server*

### Context

- Hardware: *odroid hc1 (armhf) debian buster*
- YunoHost version: 4.3.6.2
- I have access to my server: *Through SSH | through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *yes*
  - If yes, please explain: 
     - ynh in lxc container
     - whatsapp beta               
- Using, or trying to install package version/branch: master ()0.2.3

### Steps to reproduce

- *install* 
- *login*
-> message appear *Failed to log in: unexpected connection event from server*

- then : *ping*
->Connected to WhatsApp, but not logged in.
- then : *login*
-> Failed to log in: unexpected connection event from server

### Expected behavior

*present a qr code*

### Logs

*[Failed to log in: unexpected connection event from server](https://paste.yunohost.org/zonawemiqi)*

**Comment by nathanael-h** [comment]
There is a newer version, not yet packaged https://github.com/mautrix/whatsapp/releases I do not know if it fixes this issue. I won't have time soon to test it.

**Comment by yajo** [comment]
It seems that latest version should fix it: https://github.com/mautrix/whatsapp/issues/447#issuecomment-1044178221

Although he doesn't explain in which commit it's fixed, but the issue started happening like 2 days ago, so I guess it must be https://github.com/mautrix/whatsapp/releases/tag/v0.2.4.

**Comment by L-S-2020** [comment]
It's already fixed, so just update the Bridge with Yunohost and it should work.

**Comment by tituspijean** [comment]
Feel free to reopen if the issue is not fixed.
