### ISSUE TITLE
testing branch version

### ISSUE THREAD

**Issue by zunami** [YunoHost-Apps/mautrix_whatsapp_ynh#52]
the version [0.3.1](https://github.com/mautrix/whatsapp/releases/tag/v0.3.1) ist out now
is it possible to start this in the test area?

**Comment by thardev** [comment]
Hi @zunami
I'll merge v0.3.0 soon because it was blocked by Synapse but I think I can safely merge it to unblock it and start v0.3.1 afterwards.

**Comment by thardev** [comment]
I merged v0.3.0 now to testing since the pipeline is taking super long and I think it can be safely merged to testing at least. 
Also manually tried on a Raspi and was working fine

**Comment by e-jim** [comment]
Hello @thardev . 

I don't know any better, but since version [0.4](https://github.com/mautrix/whatsapp/releases/tag/v0.4.0) is already out, wouldn't it be easier to directly jump to that version?

Just asking and trying to be helpful, not to push you.

**Comment by zunami** [comment]
that is correct why was not immediately increased to 0.4

**Comment by thardev** [comment]
@e-jim Version v0.4.0 is on the way thanks to @Gredin67 :)
