### ISSUE TITLE
Missing ynh_use_logrotate --nonappend arg in the upgrade script

### ISSUE THREAD

**Issue by Salamandar** [YunoHost-Apps/mautrix_whatsapp_ynh#59]
The upgrade script is missing `--nonappend` argument to ynh_use_logrotate.

What is happening here is that the /etc/logrotate.d/mautrix_whatsapp file now contains twice the configuration, and logrotate complains about it.
```
$ sudo /usr/sbin/logrotate /etc/logrotate.conf
error: mautrix_signal:20 duplicate log entry for /var/log.hdd/mautrix_signal/mautrix_signal.log
error: found error in file mautrix_signal, skipping
error: mautrix_whatsapp:21 duplicate log entry for /var/log.hdd/mautrix_whatsapp/mautrix_whatsapp.log
error: found error in file mautrix_whatsapp, skipping
```

You should add this argument to the upgrade script.

If people (like me) already have this bug, the next upgrade will cleanup the issue because `--nonappend` overwrites the file.

**Comment by thardev** [comment]
Hi @Salamandar 
Thanks for the report :) I'll take care of it ASAP this week

**Comment by Salamandar** [comment]
No prob' !

**Comment by thardev** [comment]
@Salamandar #60 is merged on testing now, if you can test it that would be great and we can close this :)

**Comment by Salamandar** [comment]
It's --nonappend, not --non-append (it's supported for legacy compat)
See https://github.com/YunoHost/yunohost/blob/6fc6a2ba4c17434803cea2553a3dc7c51cedd338/data/helpers.d/logrotate#L18

**Comment by thardev** [comment]
yes, I saw it, for some reason on my machine with Yuno 4.3.6.3 (stable) wasn't working with `--nonappend` but I'll change it and test further maybe I was doing something wrong...

**Comment by thardev** [comment]
@Salamandar so I tested on my prod box with latest Yuno 11.0.7 and seems that it doesn't work with `--nonappend` :(
But with `--non-append` it worked so not really sure what's going on...

**Comment by Gredin67** [comment]
#62
