### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by centralscrutinizer21** [YunoHost-Apps/mautrix_whatsapp_ynh#70]
Installation fails probably because of an error in the installation script

- Hardware: Raspberry Pi 4 at home
- YunoHost version: 11.0.9.12 (stable)
- I have access to my server: Through SSH | through the webadmin 
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no

### Steps to reproduce

``sudo yunohost app install https://github.com/YunoHost-Apps/mautrix_whatsapp_ynh/tree/testing --debug
``   
### Logs

https://paste.yunohost.org/raw/powidisido

**Comment by thardev** [comment]
Hi @centralscrutinizer21 :)

I checked the logs and the issue and seems that the error comes from this script from Synapse package:
https://github.com/YunoHost-Apps/synapse_ynh/blob/master/sources/update_synapse_for_appservice.sh
So I suggest the following:

- Do you have Synapse installed? If no, install it and then try again Mautrix Whatsapp installation.
- If yes, could you try reinstalling it and then retry Mautrix Whatsapp installation?

**Comment by centralscrutinizer21** [comment]
Hi @thardev  I wanted to test it on a different machine with a different architecture and the installation went ok with the testing branch.
So yes it could be related to a bad restoration of synapse after the migration to Bullseye.
I will try to unistall and reinstall synapse, and then proceed with the installation of mautrix-whatsapp.
Do you have any suggestion on how to do that without loosing all the synapse configurations? (rooms, spaces, users etc.)

**Comment by centralscrutinizer21** [comment]
@thardev nevermind. Your suggestion was really helpful, instead of removing and reinstalling synapse I just did `yunohost app upgrade -F synapse` that repaired the configuration, and after that mautrix-whatsapp from testing installed just fine! Thanks for your help

**Comment by thardev** [comment]
Glad that I could help :) 👍
