### ISSUE TITLE
Set e2be after install

### ISSUE THREAD

**Issue by Thatoo** [YunoHost-Apps/mautrix_whatsapp_ynh#77]
Hello,

Is it possible to set e2be after install if we didn't do it at install time?
If yes, could you explain how?
Could be worthy writing it down the readme maybe.

**Comment by thardev** [comment]
Hi @Thatoo

It should be possible for sure, you just need to edit the `config.yaml` file and find these lines:
https://github.com/YunoHost-Apps/mautrix_whatsapp_ynh/blob/aa421e61f99f25a1f373bcb54b986f9c00416579/conf/config.yaml#L319-L329
There you can edit the `allow` and maybe `default` and set it to true. Then save and restart the service.
I'll add an entry to the docs for explaining this better.

When #74 is merged it would be much easier to configure it.

**Comment by thardev** [comment]
Hi @Thatoo

A section has been added to the docs regarding e2be :)
Let me know if it helps and feel free to close this issue

**Comment by thardev** [comment]
Hi @Thatoo
Will close this for now, feel free to reopen it :)
