### ISSUE TITLE
users cannot use the bridge due to miss configuration or not working keyword

### ISSUE THREAD

**Issue by rosbeef** [YunoHost-Apps/mautrix_whatsapp_ynh#83]
### Describe the bug.
i tried to login whatsapp from one of my non admin user,and he had no permission to bridge.
In the config file the value for authorized user  was "domain".
The brige does not allow homeserver users to brige

i had to set the domain as "my.domain.tld" in the config file.

### Expected behavior

*config should specify explicitly the domain not the word "domain"*
Maybe getting the server_domain from synapse app or asking user to select a local domain from list (using a domain field in the manifest).

**Comment by Gredin67** [comment]
`domain` should work https://github.com/YunoHost-Apps/mautrix_whatsapp_ynh/blob/expose-config-panel/conf/config.yaml#L395

**Comment by rosbeef** [comment]
So I don't understand why it was not working in my case 🤔 I had to set it manually.

**Comment by thardev** [comment]
Hi @rosbeef 

I think you are right, I have checked the source code from the mautrix_whatsapp repo and it seems that [this validation](https://github.com/mautrix/whatsapp/commit/ec86c490a368acf56ae09e2778f1b1a515b0dfba) was added some months ago, I guess the use of the key `domain` never worked (?) but with that validation we have to use now a valid `domain.tld` value.
Thanks for the report, I'll take care of fixing it :)

**Comment by thardev** [comment]
Hi @rosbeef 

In order to fix this I improved the descriptions of the manifest questions. For now, this is the only way we can avoid that situation you have had, maybe if needed, in the future we can add some sort of validation on the install script to avoid invalid values :)
I'll close this for now, feel free to reopen it for further questions 🙂
