### ISSUE TITLE
After upgrading, service gives error "password authentication failed"

### ISSUE THREAD

**Issue by jeffreytigch** [YunoHost-Apps/mautrix_whatsapp_ynh#84]
### Describe the bug

When upgrading mautrix_whatsapp via Yunohost GUI, the service does not run anymore, failing on starting. Gives an error that the password is incorrect.

### Context

- Hardware: local
- YunoHost version: 11.0.11
- I have access to my server: webadmin, ssh
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: yes
  - If yes, please explain: I tried reinstalling the app. This helped to solve the problem, but meant I had to recreate all of my rooms. This is not a feasible option. I also tried to add a password in the config.yaml and add this as per these instructions: https://blog.dtpnk.tech/en/matrix-reset-password-synapse/. Undid the actions because it did not work.
- Using, or trying to install package version/branch: 0.8.0

### Steps to reproduce

- Upgrade mautrix_whatsapp
    ```sh
    sudo yunohost app upgrade mautrix_whatsapp
    ```

### Expected behavior

Mautrix_whatsapp starting as normally

### Logs

Jan 11 15:26:24 systemd[1]: Started Matrix Whatsapp Bridge.
Jan 11 15:26:24 mautrix-whatsapp[1689769]: [Jan 11, 2023 15:26:24] [INFO] Initializing mautrix-whatsapp 0.8.0 (Dec 16 2022, 19:11:50 with go1.19.4)
Jan 11 15:26:24 mautrix-whatsapp[1689769]: [Jan 11, 2023 15:26:24] [INFO] Bridge initialization complete, starting...
Jan 11 15:26:24 mautrix-whatsapp[1689769]: panic: failed to check if table exists: pq: password authentication failed for user "mautrix_whatsapp"
Jan 11 15:26:24 mautrix-whatsapp[1689769]: goroutine 1 [running]:
Jan 11 15:26:24 mautrix-whatsapp[1689769]: maunium.net/go/mautrix/util/dbutil.(*Database).tableExistsNoError(0xc000166060?, {0x10f3b7e?, 0x7fe1befae158?})
Jan 11 15:26:24 mautrix-whatsapp[1689769]:         /builds/mautrix/whatsapp/.cache/pkg/mod/maunium.net/go/mautrix@v0.12.4/util/dbutil/upgrades.go:58 +0x73
Jan 11 15:26:24 mautrix-whatsapp[1689769]: maunium.net/go/mautrix/util/dbutil.(*Database).checkDatabaseOwner(0xc000504700)
Jan 11 15:26:24 mautrix-whatsapp[1689769]:         /builds/mautrix/whatsapp/.cache/pkg/mod/maunium.net/go/mautrix@v0.12.4/util/dbutil/upgrades.go:73 +0x6c
Jan 11 15:26:24 mautrix-whatsapp[1689769]: maunium.net/go/mautrix/util/dbutil.(*Database).Upgrade(0xc000504700)
Jan 11 15:26:24 mautrix-whatsapp[1689769]:         /builds/mautrix/whatsapp/.cache/pkg/mod/maunium.net/go/mautrix@v0.12.4/util/dbutil/upgrades.go:107 +0x33
Jan 11 15:26:24 mautrix-whatsapp[1689769]: maunium.net/go/mautrix/bridge.(*Bridge).start(0xc000100400)
Jan 11 15:26:24 mautrix-whatsapp[1689769]:         /builds/mautrix/whatsapp/.cache/pkg/mod/maunium.net/go/mautrix@v0.12.4/bridge/bridge.go:476 +0x7d
Jan 11 15:26:24 mautrix-whatsapp[1689769]: maunium.net/go/mautrix/bridge.(*Bridge).Main(0xc000100400)
Jan 11 15:26:24 mautrix-whatsapp[1689769]:         /builds/mautrix/whatsapp/.cache/pkg/mod/maunium.net/go/mautrix@v0.12.4/bridge/bridge.go:588 +0x489
Jan 11 15:26:24 mautrix-whatsapp[1689769]: main.main()
Jan 11 15:26:24 mautrix-whatsapp[1689769]:         /builds/mautrix/whatsapp/main.go:283 +0x33c
Jan 11 15:26:24 systemd[1]: mautrix_whatsapp.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jan 11 15:26:24 systemd[1]: mautrix_whatsapp.service: Failed with result 'exit-code'.

**Comment by thardev** [comment]
Hi @jeffreytigch 

Could you kindly tell me which version of `mautrix_whatsapp` was the previous one before the upgrade?

**Comment by Gredin67** [comment]
I think I ran into the same issue upgrading from [0.2.3](https://github.com/YunoHost-Apps/mautrix_whatsapp_ynh/blob/8d950632d001e03866b841f71ad541beb7ca9d09/scripts/restore) (or 0.5 I'm not sure).
I identified the following issue: 
- best practice in yunohost packaging nowadays is to call 
  - `db_pwd=$(ynh_app_setting_get --app=$app --key=psqlpwd)` 
  - without having any `ynh_app_setting_set --app=$app --key=psqlpwd`
  - I don't understand exactly how the password is set/backup
- But in previous versions of the package we had
  - `db_pwd=$(ynh_app_setting_get --app=$app --key=db_pwd)`
  - with `ynh_app_setting_set --app=$app --key=db_pwd  --value=$db_pwd`

So there would be some cleanup and migrations to correct in scripts.

If the `mautrix_whatsapp` DB is lost at upgrade, or connection impossible. There is a workaround to restore the DB manually from the pre-upgrade backup dump. After extracting the .tar, do something like: 
```
db_pwd=$(ynh_app_setting_get --app=$app --key=db_pwd)
db_name=mautrix_whatsapp
db_user=$db_name
ynh_psql_setup_db --db_user=$db_user --db_name=$db_name --db_pwd=$db_pwd
ynh_psql_execute_file_as_root --file="./apps/mautrix_whatsapp/backup/db.sql" --database=$db_name
```

For me I was then able to connect but lost all portal-rooms

**Comment by Gredin67** [comment]
edit: I'm afraid you've lost you're database due to a bug in the upgrade script, see https://github.com/YunoHost-Apps/mautrix_whatsapp_ynh/pull/85
Thus you should check if your database contains data. If not try to find a non-empty dumb in your backups to restore an older version of the DB. Note that if you restore a DB of a version of the bridge older that 0.4.0, then you first have to upgrade to 0.4.0 before uprgading to a more recent version.

**Comment by thardev** [comment]
I see, this might be similar to the issue we had in `mautrix_telegram` package...
I'll apply the same fix as I did there with this PR https://github.com/YunoHost-Apps/mautrix_telegram_ynh/pull/43/files
That should solve it

**Comment by jeffreytigch** [comment]
I think it was set up with 0.7.1. Had the same problem with the signal and telegram packages. 

Unfortunate to see I've lost my data, but good to see the root cause has been found. Unfortunately, I am not that skilled to help out with fixing the bug, so I will be waiting for a fix.

**Comment by thardev** [comment]
Hi @jeffreytigch 

I'll close this because it was fixed during the config panel implementation, it should work fine for now, feel free to reopen if the issue persists :)

**Comment by nathanael-h** [comment]
Hello, I upgraded to v 0.8.5~ynh1 and faced this issue. 
In `/etc/yunohost/apps/mautrix_whatsapp/settings.yml` password for db is empty: `db_pwd: ''` and thus in config file I see no password `uri: postgres://mautrix_whatsapp:@localhost:5432/mautrix_whatsapp` in `/opt/yunohost/mautrix_whatsapp/config.yaml`

**Comment by thardev** [comment]
Hi @nathanael-h 

Could you tell me from which version you were upgrading from?

**Comment by nathanael-h** [comment]
Hey, it was from `0.8.2~ynh2   to  0.8.5~ynh1`

**Comment by thardev** [comment]
Hmmm it is a bit strange because this was supposed to be solved in this lines:
https://github.com/YunoHost-Apps/mautrix_whatsapp_ynh/blob/39e576ee114e337bb640daaa9c02bb8afce3e325/scripts/upgrade#L105-L109

So I don't know what could have caused it on your side, do you have any logs?
Also, is it already solved or do you need help?

**Comment by nathanael-h** [comment]
Strange, indeed. I fixed the issue myself thanks to this snippet of code.
