### ISSUE TITLE
Photos, attachments and voice notes unavailable on Whatsapp

### ISSUE THREAD

**Issue by elpibegeek** [YunoHost-Apps/mautrix_whatsapp_ynh#90]
Hello! Whatsapp bridge is unavailable to send correctly photos, videos, voice notes and files

When someone receive the image I send, It's impossible to download it via Whatsapp official app

![Screenshot_20230224_144709_WhatsApp](https://user-images.githubusercontent.com/96203496/221251858-a7285389-f571-45bb-86a7-89a04a08749c.jpg)

I was looking for some answers in the Github's official repository of Mautrix and I found that this is a bug, please see the link below
https://github.com/mautrix/whatsapp/issues/595
And It was fixed here with the addition of some missing fields
https://github.com/mautrix/whatsapp/commit/96092af492bb59a94b56f60725e008fd3c5186df

Do this package needs to be updated with these corrections in orden to make multimedia send properly?

Just in case, I will add my yunopaste log here :)
`LOGFILE: journalctl
-- Journal begins at Thu 2022-12-15 21:26:08 -03, ends at Fri 2023-02-24 14:45:01 -03. --
Feb 23 23:41:01 mautrix-whatsapp[653259]: [Feb 23, 2023 23:41:01] [Portal/5491157680287@s.whatsapp.net-5491155741324@s.whatsapp.net/ERROR] Failed to bridge media for 19712D3BE042C572E3C577D72A0E24BC: failed to upload media: failed to POST /_matrix/media/v3/upload: M_UNKNOWN (HTTP 500): Internal server error
Feb 23 23:41:17 mautrix-whatsapp[653259]: [Feb 23, 2023 23:41:17] [Portal/5491157680287@s.whatsapp.net-5491155741324@s.whatsapp.net/ERROR] Failed to bridge media for 4A96EE925CB5B65AFE57B5D0E0E26AFF: failed to upload media: failed to POST /_matrix/media/v3/upload: M_UNKNOWN (HTTP 500): Internal server error
Feb 23 23:50:27 mautrix-whatsapp[653259]: [Feb 23, 2023 23:50:27] [Portal/5491157680287@s.whatsapp.net-5491155741324@s.whatsapp.net/ERROR] Failed to bridge media for E9ED549DDE7A431787A3AA6F885A5500: failed to upload media: failed to POST /_matrix/media/v3/upload: M_UNKNOWN (HTTP 500): Internal server error
Feb 23 23:55:44 mautrix-whatsapp[653259]: [Feb 23, 2023 23:55:44] [Portal/status@broadcast-5491155741324@s.whatsapp.net/ERROR] Failed to bridge media for E6B6711BC4E898210DB0B11C9F4515CC: failed to upload media: failed to POST /_matrix/media/v3/upload: M_UNKNOWN (HTTP 500): Internal server error
Feb 24 00:26:42 mautrix-whatsapp[653259]: [Feb 24, 2023 00:26:42] [Portal/5491157680287@s.whatsapp.net-5491155741324@s.whatsapp.net/ERROR] Failed to bridge media for 0299D13729E4C165B0E4D44E36054F5F: failed to upload media: failed to POST /_matrix/media/v3/upload: M_UNKNOWN (HTTP 500): Internal server error
Feb 24 00:29:49 mautrix-whatsapp[653259]: [Feb 24, 2023 00:29:49] [Portal/5491157680287@s.whatsapp.net-5491155741324@s.whatsapp.net/ERROR] Failed to bridge media for 59A5216BE6E2A351E129B1F47A092CCE: failed to upload media: failed to POST /_matrix/media/v3/upload: M_UNKNOWN (HTTP 500): Internal server error
Feb 24 00:42:24 mautrix-whatsapp[653259]: [Feb 24, 2023 00:42:24] [Portal/status@broadcast-5491155741324@s.whatsapp.net/ERROR] Failed to bridge media for 3AA95B0B235ABE9FB6FE: failed to upload media: failed to POST /_matrix/media/v3/upload: M_UNKNOWN (HTTP 500): Internal server error
Feb 24 02:56:26 systemd[1]: Stopping Matrix Whatsapp Bridge...
Feb 24 02:56:26 mautrix-whatsapp[653259]: [Feb 24, 2023 02:56:26] [INFO] Interrupt received, stopping...
Feb 24 02:56:26 mautrix-whatsapp[653259]: [Feb 24, 2023 02:56:26] [INFO] Bridge stopped.
Feb 24 02:56:26 systemd[1]: mautrix_whatsapp.service: Succeeded.
Feb 24 02:56:26 systemd[1]: Stopped Matrix Whatsapp Bridge.
Feb 24 02:56:26 systemd[1]: mautrix_whatsapp.service: Consumed 19.089s CPU time.
Feb 24 02:56:26 systemd[1]: Started Matrix Whatsapp Bridge.
Feb 24 02:56:26 mautrix-whatsapp[671800]: [Feb 24, 2023 02:56:26] [INFO] Initializing mautrix-whatsapp 0.8.0 (Dec 16 2022, 19:11:40 with go1.19.4)
Feb 24 02:56:26 mautrix-whatsapp[671800]: [Feb 24, 2023 02:56:26] [INFO] Bridge initialization complete, starting...
Feb 24 02:56:26 mautrix-whatsapp[671800]: [Feb 24, 2023 02:56:26] [Database/INFO] Database currently on v53, latest: v53
Feb 24 02:56:26 mautrix-whatsapp[671800]: [Feb 24, 2023 02:56:26] [Database/StateStore/INFO] Database currently on v3, latest: v3
Feb 24 02:56:26 mautrix-whatsapp[671800]: [Feb 24, 2023 02:56:26] [Matrix/INFO] Listening on 0.0.0.0:8449
Feb 24 02:56:26 mautrix-whatsapp[671800]: [Feb 24, 2023 02:56:26] [INFO] Bridge started!
Feb 24 02:56:27 mautrix-whatsapp[671800]: [Feb 24, 2023 02:56:27] [WARN] Bridge is using outdated WhatsApp web protocol and probably doesn't work anymore (2.2246.10, latest is 2.2307.10)
Feb 24 02:56:27 mautrix-whatsapp[671800]: [Feb 24, 2023 02:56:27] [User/@kndgonza:chat.elpibegeek.stream/Client/INFO] Successfully authenticated
Feb 24 03:01:19 systemd[1]: Stopping Matrix Whatsapp Bridge...
Feb 24 03:01:19 mautrix-whatsapp[671800]: [Feb 24, 2023 03:01:19] [INFO] Interrupt received, stopping...
Feb 24 03:01:19 mautrix-whatsapp[671800]: [Feb 24, 2023 03:01:19] [INFO] Bridge stopped.
Feb 24 03:01:19 systemd[1]: mautrix_whatsapp.service: Succeeded.
Feb 24 03:01:19 systemd[1]: Stopped Matrix Whatsapp Bridge.
-- Boot 2bd25a056ef440bd8485ed636a9f8b9b --
Feb 24 03:01:51 systemd[1]: Started Matrix Whatsapp Bridge.
Feb 24 03:01:51 mautrix-whatsapp[1458]: [Feb 24, 2023 03:01:51] [INFO] Initializing mautrix-whatsapp 0.8.0 (Dec 16 2022, 19:11:40 with go1.19.4)
Feb 24 03:01:51 mautrix-whatsapp[1458]: [Feb 24, 2023 03:01:51] [INFO] Bridge initialization complete, starting...
Feb 24 03:01:51 mautrix-whatsapp[1458]: [Feb 24, 2023 03:01:51] [Database/INFO] Database currently on v53, latest: v53
Feb 24 03:01:51 mautrix-whatsapp[1458]: [Feb 24, 2023 03:01:51] [Database/StateStore/INFO] Database currently on v3, latest: v3
Feb 24 03:01:51 mautrix-whatsapp[1458]: [Feb 24, 2023 03:01:51] [Matrix/Bot/WARN] Request #1 failed: HTTP 502, retrying in 4 seconds
Feb 24 03:01:55 mautrix-whatsapp[1458]: [Feb 24, 2023 03:01:55] [Matrix/Bot/WARN] Request #1 failed: HTTP 502, retrying in 8 seconds
Feb 24 03:02:03 mautrix-whatsapp[1458]: [Feb 24, 2023 03:02:03] [Matrix/INFO] Listening on 0.0.0.0:8449
Feb 24 03:02:03 mautrix-whatsapp[1458]: [Feb 24, 2023 03:02:03] [INFO] Bridge started!
Feb 24 03:02:04 mautrix-whatsapp[1458]: [Feb 24, 2023 03:02:04] [WARN] Bridge is using outdated WhatsApp web protocol and probably doesn't work anymore (2.2246.10, latest is 2.2307.10)
Feb 24 03:02:05 mautrix-whatsapp[1458]: [Feb 24, 2023 03:02:05] [User/@kndgonza:chat.elpibegeek.stream/Client/INFO] Successfully authenticated
Feb 24 03:54:08 mautrix-whatsapp[1458]: [Feb 24, 2023 03:54:08] [User/@kndgonza:chat.elpibegeek.stream/Client/INFO] Successfully authenticated
Feb 24 11:53:26 mautrix-whatsapp[1458]: [Feb 24, 2023 11:53:26] [User/@kndgonza:chat.elpibegeek.stream/Client/ERROR] Failed to handle retry receipt for 5491169452231-1566757635@g.us/3EB07F011EEBA337C76B from 5491144014215.0:24@s.whatsapp.net: couldn't find message 3EB07F011EEBA337C76B
Feb 24 11:56:29 mautrix-whatsapp[1458]: [Feb 24, 2023 11:56:29] [User/@kndgonza:chat.elpibegeek.stream/Client/ERROR] Failed to handle retry receipt for 5491169452231-1566757635@g.us/3EB05C41923ADFEE3B40 from 5491144014215.0:24@s.whatsapp.net: couldn't find message 3EB05C41923ADFEE3B40
Feb 24 12:01:21 mautrix-whatsapp[1458]: [Feb 24, 2023 12:01:21] [Portal/5491135703512@s.whatsapp.net-5491155741324@s.whatsapp.net/ERROR] Failed to bridge media for F0D10FD460036455D2: Get "https://mmg.whatsapp.net/v/t62.7119-24/12475188_620697449890263_411359273707196957_n.enc?ccb=11-4&oh=01_AdQT79dEy4N3xquQ1PMa4lhPf1ekNaXSsVIU-htUs6h4Ew&oe=64203699&mms3=true": dial tcp [2a03:2880:f230:c5:face:b00c:0:167]:443: connect: network is unreachable
Feb 24 12:06:23 mautrix-whatsapp[1458]: [Feb 24, 2023 12:06:23] [Portal/120363021560195759@g.us/INFO] Room seems to be empty, cleaning up...
Feb 24 12:06:24 mautrix-whatsapp[1458]: [Feb 24, 2023 12:06:24] [Portal/120363021560195759@g.us/WARN] Failed to kick @kndgonza:chat.elpibegeek.stream from !RbEWVIzCfHIxarYfxW:chat.elpibegeek.stream: failed to POST /_matrix/client/v3/rooms/!RbEWVIzCfHIxarYfxW:chat.elpibegeek.stream/kick: M_FORBIDDEN (HTTP 403): The target user is not in the room
Feb 24 12:06:24 mautrix-whatsapp[1458]: [Feb 24, 2023 12:06:24] [Portal/120363021560195759@g.us/ERROR] Failed to get Matrix user list to determine if portal needs to be cleaned up: failed to get member list: failed to GET /_matrix/client/v3/rooms/!RbEWVIzCfHIxarYfxW:chat.elpibegeek.stream/joined_members: M_FORBIDDEN (HTTP 403): Appservice not in room
Feb 24 12:20:51 mautrix-whatsapp[1458]: [Feb 24, 2023 12:20:51] [User/@kndgonza:chat.elpibegeek.stream/Client/WARN] Got 503 stream error, assuming automatic reconnect will handle it
Feb 24 12:20:51 mautrix-whatsapp[1458]: [Feb 24, 2023 12:20:51] [User/@kndgonza:chat.elpibegeek.stream/Client/WARN] Received stream end frame
Feb 24 12:20:51 mautrix-whatsapp[1458]: [Feb 24, 2023 12:20:51] [User/@kndgonza:chat.elpibegeek.stream/Client/Socket/ERROR] Error reading from websocket: websocket: close 1006 (abnormal closure): unexpected EOF
Feb 24 12:20:53 mautrix-whatsapp[1458]: [Feb 24, 2023 12:20:53] [User/@kndgonza:chat.elpibegeek.stream/Client/INFO] Successfully authenticated
Feb 24 14:07:22 mautrix-whatsapp[1458]: [Feb 24, 2023 14:07:22] [Portal/120363044340432505@g.us/INFO] Syncing portal for @kndgonza:chat.elpibegeek.stream`

**Comment by yajo** [comment]
So, it should be fixed with https://github.com/YunoHost-Apps/mautrix_whatsapp_ynh/pull/88.

**Comment by thardev** [comment]
Hi @elpibegeek 

I've been experiencing this as well, I thought it was a problem of Element but now I see it is not. I'll try to handle the update as soon as possible. 👍

**Comment by thardev** [comment]
Hi @elpibegeek @yajo 

v0.8.2 is on `testing` branch now so you can try to use it and see if it fixes this issue 🙂

**Comment by elpibegeek** [comment]
The bug is fixed now! :D Do you need any logs?

Thanks!
Gonza

**Comment by thardev** [comment]
Nope, if it is working as expected, you can just close this :)
